<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; line-height: 1.7; }
        .page { padding: 50px 60px; }

        .header { text-align: center; border-bottom: 2px solid #0f172a; padding-bottom: 24px; margin-bottom: 32px; }
        .logo { font-size: 14px; color: #1e40af; font-weight: 700; letter-spacing: 2px; margin-bottom: 8px; }
        .deed-title { font-size: 20px; font-weight: 700; color: #0f172a; text-transform: uppercase; letter-spacing: 2px; }
        .deed-sub { font-size: 12px; color: #475569; margin-top: 4px; }

        h2 { font-size: 12px; font-weight: 700; color: #0f172a; text-transform: uppercase; letter-spacing: 1px; margin: 24px 0 10px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
        p { margin-bottom: 10px; font-size: 11px; color: #334155; text-align: justify; }
        .indent { margin-left: 20px; }

        .parties-table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        .parties-table th { background: #f1f5f9; padding: 8px 12px; text-align: left; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #475569; border: 1px solid #e2e8f0; }
        .parties-table td { padding: 8px 12px; border: 1px solid #e2e8f0; font-size: 11px; vertical-align: top; }
        .parties-table tr:nth-child(even) td { background: #f8fafc; }

        .clause { margin-bottom: 14px; }
        .clause-num { font-weight: 700; }

        .signature-section { margin-top: 40px; }
        .sig-grid { width: 100%; margin-top: 20px; }
        .sig-block { float: left; width: 45%; margin-bottom: 24px; }
        .sig-block.right { float: right; }
        .sig-line { border-bottom: 1px solid #0f172a; width: 80%; margin: 40px 0 6px; }
        .sig-label { font-size: 10px; color: #475569; }
        .sig-name { font-size: 11px; font-weight: 700; margin-top: 2px; }
        .clearfix::after { content: ''; display: table; clear: both; }

        .notice-box { background: #fef9c3; border: 1px solid #fde047; border-radius: 4px; padding: 10px 14px; margin: 20px 0; font-size: 10px; color: #713f12; }
        .footer { border-top: 1px solid #e2e8f0; margin-top: 30px; padding-top: 12px; font-size: 9px; color: #94a3b8; text-align: center; }
        .page-number { text-align: right; font-size: 9px; color: #94a3b8; margin-bottom: 8px; }
    </style>
</head>
<body>
<div class="page">

    <div class="header">
        <div class="logo">RegE</div>
        <div class="deed-title">Partnership Deed</div>
        <div class="deed-sub">This Agreement is made on {{ \Carbon\Carbon::parse($commencement_date)->format('d F Y') }}</div>
    </div>

    <div class="notice-box">
        ⚠ <strong>Important Notice:</strong> This document is a template generated by the RegE platform for reference purposes only.
        It has not been reviewed by a qualified advocate. Before executing this deed, consult a licensed Kenyan advocate
        to ensure it meets your specific legal requirements and complies with the Partnership Act (Cap 29, Laws of Kenya).
    </div>

    <h2>1. Parties to This Agreement</h2>
    <p>This Partnership Deed is entered into between the following individuals (hereinafter collectively referred to as "the Partners"):</p>

    <table class="parties-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>ID / Passport No.</th>
                <th>Share (%)</th>
                <th>Role</th>
            </tr>
        </thead>
        <tbody>
            @foreach($partners as $i => $partner)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td>{{ $partner['name'] }}</td>
                <td>{{ $partner['id_no'] }}</td>
                <td>{{ $partner['share'] }}%</td>
                <td>{{ $i === 0 ? 'Managing Partner' : 'Partner' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <h2>2. Name and Nature of Business</h2>
    <p>The Partners hereby agree to carry on business in partnership under the name
    <strong>"{{ $company->company_name }}"</strong>
    (hereinafter referred to as "the Firm").</p>
    <p>The nature of the business shall be:
    {{ $company->company_description ?? $company->category?->name ?? 'as mutually agreed by the Partners' }}.
    </p>

    <h2>3. Commencement and Duration</h2>
    <p>The partnership shall commence on <strong>{{ \Carbon\Carbon::parse($commencement_date)->format('d F Y') }}</strong>
    and shall continue until dissolved by mutual agreement or by operation of law.</p>

    <h2>4. Principal Place of Business</h2>
    <p>The principal place of business of the Firm shall be at:
    <strong>{{ $business_address }}</strong>, or at such other place as the Partners may mutually agree upon from time to time.</p>

    <h2>5. Capital Contributions</h2>
    <p>The capital of the partnership shall be contributed by the Partners in proportion to their respective profit/loss sharing ratios
    as set out in Clause 1 above. Any additional capital requirements shall be contributed by the Partners in the same proportions
    unless otherwise agreed in writing.</p>

    <h2>6. Profit and Loss Sharing</h2>
    <p>The net profits and losses of the partnership shall be shared among the Partners in the following proportions:</p>
    <div class="indent">
        @foreach($partners as $partner)
        <p>{{ $partner['name'] }}: <strong>{{ $partner['share'] }}%</strong></p>
        @endforeach
    </div>

    <h2>7. Management and Decision Making</h2>
    <p>7.1 Each Partner shall have equal rights in the management and conduct of the partnership business unless otherwise agreed in writing.</p>
    <p>7.2 Decisions on ordinary business matters shall be made by a simple majority. Decisions on matters affecting the fundamental
    nature of the business, admission of new partners, or disposal of substantial business assets shall require unanimous consent.</p>
    <p>7.3 The Managing Partner named in Clause 1 shall have authority to sign documents and execute contracts on behalf of the Firm
    up to a value of KES 100,000 without requiring the signature of the other Partners.</p>

    <h2>8. Banking</h2>
    <p>The Firm's funds shall be deposited in a bank account opened in the name of the Firm. All withdrawals above KES 50,000
    shall require the signature of at least two Partners.</p>

    <h2>9. Accounts and Records</h2>
    <p>Proper books of account shall be maintained at the principal place of business. The accounts shall be made up to the 31st
    December in each year and a copy shall be furnished to each Partner within 90 days of the close of each financial year.</p>

    <h2>10. Admission of New Partners</h2>
    <p>No new Partner shall be admitted to the Firm without the unanimous written consent of all existing Partners.</p>

    <h2>11. Retirement and Dissolution</h2>
    <p>11.1 Any Partner may retire from the Firm by giving not less than three (3) months written notice to the other Partners.</p>
    <p>11.2 The Firm shall be dissolved upon the mutual written agreement of all Partners, or upon the occurrence of any event
    required by law.</p>
    <p>11.3 Upon dissolution, the assets of the Firm shall be applied first in payment of debts, then to repay capital contributions,
    and any surplus shall be divided in the profit-sharing proportions specified in Clause 6.</p>

    <h2>12. Dispute Resolution</h2>
    <p>Any disputes arising from this Deed shall be resolved first by mediation between the Partners. If mediation fails,
    disputes shall be referred to arbitration in accordance with the Arbitration Act (Cap 49, Laws of Kenya).
    The seat of arbitration shall be Nairobi, Kenya.</p>

    <h2>13. Governing Law</h2>
    <p>This Deed shall be governed by and construed in accordance with the laws of Kenya, including the Partnership Act
    (Cap 29, Laws of Kenya).</p>

    {{-- Signatures --}}
    <div class="signature-section">
        <h2>14. Execution</h2>
        <p>IN WITNESS WHEREOF, the Partners have signed this Deed on the date first written above.</p>

        <div class="sig-grid clearfix">
            @foreach($partners as $i => $partner)
            <div class="sig-block {{ $i % 2 === 1 ? 'right' : '' }}">
                <div class="sig-line"></div>
                <div class="sig-name">{{ $partner['name'] }}</div>
                <div class="sig-label">ID No: {{ $partner['id_no'] }}</div>
                <div class="sig-label">Share: {{ $partner['share'] }}% | Date: _______________</div>
            </div>
            @if($i % 2 === 1 && $i < count($partners) - 1)
                <div class="clearfix"></div>
            @endif
            @endforeach
        </div>
        <div class="clearfix"></div>

        <div style="margin-top: 32px; border: 1px solid #e2e8f0; border-radius: 4px; padding: 14px 18px;">
            <p style="font-weight:700; margin-bottom:8px; font-size:11px;">WITNESSED BY:</p>
            <div class="clearfix">
                <div class="sig-block">
                    <div class="sig-line"></div>
                    <div class="sig-label">Witness Name: ___________________________</div>
                    <div class="sig-label">ID No: _________________________________</div>
                    <div class="sig-label">Date: __________________________________</div>
                </div>
                <div class="sig-block right">
                    <p style="font-size:10px;color:#475569;margin-top:8px;">For official registration of this partnership,<br>
                    present this deed at the nearest BRS office<br>or via eCitizen at ecitizen.go.ke</p>
                </div>
            </div>
        </div>
    </div>

    <div class="footer">
        Generated by RegE (rege.africa) on {{ now()->format('d F Y, H:i') }} |
        Document ID: REGE/PD/{{ strtoupper(substr(md5($company->id . now()), 0, 10)) }} |
        This is a template document — consult a qualified advocate before execution.
    </div>

</div>
</body>
</html>